name: Go

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@main

    - name: Set up Go
      uses: actions/setup-go@main
      with:
        go-version: 1.19
        cache: true
        cache-dependency-path: **/go.sum

    - name: Linter
      run: |
        export PATH=$PATH:$(go env GOPATH)/bin
        go install golang.org/x/lint/golint@latest
        cd ./GO/HACKERRANK/
        golint -set_exit_status ./...

    - name: Staticcheck
      run: |
        export PATH=$PATH:$(go env GOPATH)/bin
        go install honnef.co/go/tools/cmd/staticcheck@latest
        cd ./GO/HACKERRANK/
        staticcheck ./...

    - name: Go Vet
      run: |
        cd ./GO/HACKERRANK/
        go vet -x ./...

    - name: Build
      run: |
        cd ./GO/HACKERRANK/
        go build -race -v -x ./...

    - name: Test
      run: |
        cd ./GO/HACKERRANK/
        go test -v --covermode=count --coverprofile=c.out ./...
        go tool cover -func=c.out
