name: Go

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.16

    - name: Build
      run: cd ./GO/HACKERRANK/ && go build -race -v -x ./...

    - name: Test
      run: cd ./GO/HACKERRANK/ && go test -v --covermode=count --coverprofile=c.out ./... && go tool cover -func=c.out
