name: Go

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.16

    - name: List
      run: ls -la
      
    - name: Dir
      run: pwd

    - name: Build
      run: go build -v ./GO/HACKERRANK/...

    - name: Test
      run: go test -v ./GO/HACKERRANK/...
